services:
  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    environment:
      - DB_PATH=/app/data/app.db
      - OUTPUT_DIR=/app/pub
      - SUPERADMIN_PASSWORD
    volumes:
      - db_data:/app/data
      - /srv/www/example.com/@info:/app/pub
    ports:
      - 8000:8000

volumes:
  db_data:
